[package]
name    = "stowe"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
stowe-core   = { path = "../stowe-core" }
clap         = { workspace = true }
dialoguer    = { workspace = true }
anyhow       = { workspace = true }
dirs         = { workspace = true }
tauri        = { workspace = true }
tauri-plugin-clipboard-manager = { workspace = true }
tauri-plugin-dialog = { workspace = true }
rusqlite     = { workspace = true }
serde_json   = { workspace = true }
serde        = { workspace = true }

[build-dependencies]
tauri-build  = { workspace = true }

[dev-dependencies]
tempfile = "3"
