[package]
name    = "secrets"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[[bin]]
name = "secrets"
path = "src/main.rs"

[dependencies]
secrets-core = { path = "../secrets-core" }
clap         = { workspace = true }
dialoguer    = { workspace = true }
anyhow       = { workspace = true }
